// a simple guess game 
// the number to guess is randomly generated by the program


#include <iostream>
#include <iomanip>
#include <cmath>
#include <stdlib.h>

using namespace std;



int main()
{

    int isRand, guess,Tries = 0;

    isRand = rand() % 15 +1;
    cout<<"Make a guess: "<<endl;
    cin>>guess;

    // first guess!
    Tries+=1;

    // subsequent guesses!
    while (Tries<3)
    {
        if (guess == isRand){
            cout<<"Your guessed correctly"<<endl;
            cout<<"You got it in "<<Tries<<" Tries"<<endl;
            break;
        }
        else{
            if (guess>isRand){
                cout<<"Your guess is too high!"<<endl;
            }
            else{
                cout<<"Your guess is too low!"<<endl;
            }
            cout<<"Make another guess: "<<endl;
            cin>>guess;
            Tries+=1;
        }
    }

    cout<<"You exceeded the number of tries"<<endl;
    cout<<"The correct answer would be: "<<isRand<<endl;

}
